### ISSUE TITLE
You are being watched.

### ISSUE THREAD

**Issue by Harold-Admin** [andrewmcwatters/public#11]
The government has a secret system: a machine that spies on you every hour of every day. I know, because I built it. I designed the machine to detect acts of terror, but it sees everything. Violent crimes involving ordinary people; people like you. Crimes the government considered 'irrelevant'. They wouldn't act, so I decided I would. But I needed a partner, someone with the skills to intervene. Hunted by the authorities, we work in secret. You'll never find us, but victim or perpetrator, if your number's up... we'll find you.

**Comment by nathancingram** [comment]
I'm a very private person.
